name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
  lint-pr:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - id: files
        uses: Ana06/get-changed-files@v1.2
      - name: Проверка линтером
        run: |
          npm install editorconfig-checker --global
          config=.editorconfig
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [ $changed_file == $config ]
            then
              echo "Проверка для всех файлов"
              editorconfig-checker
              break
            else
              echo "Проверка для ${changed_file}"
              editorconfig-checker ${changed_file}
            fi
          done
  lint-main:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Проверка линтером
        run: npx editorconfig-checker
