name: Frontmatter Check

on:
  workflow_run:
    workflows:
      - "YaSpeller PR"
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.pull_requests.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: 'index.md'
      - name: Проверка линтером в PR
        run: |
          files="${{ steps.files.outputs.all }}"
          if ! [[ $files == "" ]]; then
            echo "Проверка для файлов из PR"
            npx yaml-cat -f json ${{ steps.files.outputs.all }} -o result.json
            node .github/scripts/frontmatter.js
          else
            echo "В PR нет файлов для проверки"
          fi
