name: Frontmatter Check

on:
  pull_request:

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Проверка линтером в PR
        run: |
          files=$(echo "$(git diff --name-only ${{ github.event.sha }} ${{ github.event.workflow_run.head_sha }})")
          echo $files | grep -o -E ' (css|html|js|tools)/[a-z-]+/index.md' | tr '\n' ' '
          if ! [[ $files == "" ]]; then
            echo "Проверка для файлов из PR"
            npx yaml-cat -f json ${{ steps.files.outputs.all }} -o result.json
            node .github/scripts/frontmatter.js
          else
            echo "В PR нет файлов для проверки"
          fi
