name: Product Deploy

on:
  workflow_run:
    workflows:
      - "Update Dates"
    branches:
      - main
    types:
      - completed

jobs:
  product-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PATH_TO_CONTENT: ./content
    steps:
      - name: Загрузка platform
        uses: actions/checkout@v4
        with:
          repository: doka-guide/platform
      - name: Загрузка контента
        uses: actions/checkout@v4
        with:
          path: content
      - name: Загрузка кеша
        uses: actions/checkout@v4
        with:
          repository: doka-guide/cache
          path: cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Кэширование модулей
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка ключа для пользователя
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/doka_deploy"
          chmod 600 "$HOME/.ssh/doka_deploy"
          echo "${{ secrets.DEPLOY_CONFIG }}" > "$HOME/.ssh/config"
          chmod 600 "$HOME/.ssh/config"
          ssh -o StrictHostKeyChecking=no deploy@dev.doka.guide
      - name: Установка модулей
        run: npm ci
      - name: Копирование кеша
        run: cp ./cache/issues.json ./.issues.json
      - name: Сборка сайта
        run: |
          cp .env.example .env
          npm run build
      - name: Генерация карточек для социальных сетей
        run: npx gulp socialCards
      - name: Публикация сайта
        run: |
          cd dist
          rsync --exclude 'api.json' --exclude 'mail' --archive --progress --compress --delete . dev.doka.guide:/web/sites/doka.guide/www/
