name: Sort Dictionary

on:
  workflow_run:
    workflows:
      - "YaSpeller All"
    branches:
      - main
    types:
      - completed

jobs:
  sort-dictionary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
      - name: Сортировка словаря исключений
        run: node .github/scripts/sort.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Сортирует словарь исключений
          file_pattern: .yaspeller.json
          commit_user_name: Doka Dog
          commit_user_email: hi@doka.guide
          commit_author: Doka Dog <hi@doka.guide>
