name: YaSpeller PR

on:
  pull_request:

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        uses: Ana06/get-changed-files@v1.2
      - name: Проверка правописания
        run: |
          config=.yaspeller.json
          file_list=""
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == $config ]]; then
              echo "Проверяются все файлы..."
              npx yaspeller --only-errors --file-extensions ".md,.html" *
              break
            elif [[ $changed_file =~ \.(md|html)$ ]]; then
              file_list="${file_list} ${changed_file}"
              echo "Файл ${changed_file} добавлен в список для проверки."
            fi
          done
          if ! [[ $file_list == "" ]]; then
            echo "Проверяются файлы из PR..."
            npx yaspeller --only-errors ${file_list}
          fi
